apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260617-234613-4t8v3r34goxl-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260617-234613-4t8v3r34goxl.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260617-234613-4t8v3r34goxl-service
            port:
              number: 80
