apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260617-234613-4t8v3r34goxl-service
spec:
  selector:
    app: enterprise-system-20260617-234613-4t8v3r34goxl
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
